export const POINTLADDER_DEFAULT_SORT = 'name@asc';

export enum ENUM_POINTLADDER_STATUS_CODE_ERROR {
    POINTLADDER_IS_INACTIVE = 5500,
    POINTLADDER_NOT_FOUND_ERROR = 5501,
    POINTLADDER_EXIST_ERROR = 5502
}
