### LOGIN
POST https://parkinson-dev-api.medstore.com.vn/api/auth/login
Content-Type: application/json

{
    "email":"nhp213212@gmail.com",
    "password":"123456"
}

### CREATE USER
POST https://parkinson-dev-api.medstore.com.vn/api/user/create
Content-Type: application/json

{
    "email": "nhp213212@gmail.com",
    "lastName": "phu",
    "firstName": "Nguyen",
    "role": "61beb73b97439812080c7faa",
    "password": "123456",
    "phone": "098765432112"
}
### UPDATE USER
PUT http://localhost:3000/api/user/update/61c35eb73a0ba4374cafcc8c
Content-Type: application/json

{
    "lastName": "phu",
    "firstName": "Nguyen tesst",
    "phone": "0865452090"
}
### UPDATE PASSWORD
PUT http://localhost:3000/api/user/update-password/61c2b5f79f4d3a31f81bb095
Content-Type: application/json

{
    "password": "123456789",
    "passwordNew": "123456789"
}
#### GET PATIENT BY ID
GET http://localhost:3000/api/patient/61c2b5f79f4d3a31f81bb095


#### CREATE PATIENT
POST https://parkinson-dev-api.medstore.com.vn/api/patient/create
Content-Type: application/json

{
    "name": "Nguyen Huu Phu",
    "email": "nhp2132@gmail.com",
    "address": "Ha Noi",
    "phone": "0987654321",
    "message": "test message",
    "job": "doctor"
}
#### UPDATE PATIENT
PUT https://parkinson-dev-api.medstore.com.vn/api/patient/update/61c36d1ccee2244cacdd2d68
Content-Type: application/json

{
    "phone": "036920204",
    "email": "nhp2132+2@gmail.com",
    "education": "Bac",
    "nationality": "VN"
}

### CREATE, UPDATE SYMPTOMS
POST http://localhost:3000/api/symptoms/61c2b5f79f4d3a31f81bb095
Content-Type: application/json

{
    "symptoms":[
        {
            "symptom": "Co giật",
            "decrpition":" run tay"
        },
        {
            "symptom": "Co giật1",
            "decrpition":" run tay2"
        },
        {
            "symptom": "Co giật3",
            "decrpition":" run tay3"
        },
         {
            "symptom": "Co giật5",
            "decrpition":" run tay5"
        }
        
    ]
}

### DELETE SYMPTOMS
DELETE  http://localhost:3000/api/symptoms/61c35529512eff465c241486?symptom=Co giật5

