version: '3.4'

services:
  postgres:
    container_name: postgres-localmos
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: 'redis:alpine'
    container_name: redis-locamos
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq-locamos'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    env_file:
      - .env

volumes:
  psql_data:
  redis_data:
  rabbitmq_data: