export const TYPEBASE_DEFAULT_SORT = 'name@asc';

export enum ENUM_TYPEBASE_STATUS_CODE_ERROR {
    TYPEBASE_IS_INACTIVE = 5500,
    TYPEBASE_NOT_FOUND_ERROR = 5501,
    TYPEBASE_EXIST_ERROR = 5502
}
