export enum ENUM_MEDICAL_HISTORY_STATUS_CODE_ERROR {
    MEDICAL_HISTORY_NOT_FOUND_ERROR = 5400,
    MEDICAL_HISTORY_EXISTS_ERROR = 5401,
    MEDICAL_HISTORY_IS_INACTIVE = 5402,
}

export const MEDICAL_HISTORY_DEFAULT_SORT = 'name@asc';
