export const EXAMPLACE_DEFAULT_SORT = 'name@asc';

export enum ENUM_EXAMPLACE_STATUS_CODE_ERROR {
    EXAMPLACE_IS_INACTIVE = 5500,
    EXAMPLACE_NOT_FOUND_ERROR = 5501,
    EXAMPLACE_EXIST_ERROR = 5502
}
