export const EDUCATION_DEFAULT_SORT = 'name@asc';

export enum ENUM_EDUCATION_STATUS_CODE_ERROR {
    EDUCATION_IS_INACTIVE = 5500,
    EDUCATION_NOT_FOUND_ERROR = 5501,
    EDUCATION_EXIST_ERROR = 5502
}
