export const DEPARTMENT_DEFAULT_SORT = 'name@asc';

export enum ENUM_DEPARTMENT_STATUS_CODE_ERROR {
    DEPARTMENT_IS_INACTIVE = 5500,
    DEPARTMENT_NOT_FOUND_ERROR = 5501,
    DEPARTMENT_EXIST_ERROR = 5502
}
