export const EXAMRECORD_DEFAULT_SORT = 'name@asc';

export enum ENUM_EXAMRECORD_STATUS_CODE_ERROR {
    EXAMRECORD_IS_INACTIVE = 5500,
    EXAMRECORD_NOT_FOUND_ERROR = 5501,
    EXAMRECORD_EXIST_ERROR = 5502
}

export enum ENUM_EXAMRECORD_TYPE {
    KHAM_MOI = 'KHÁM MỚI',
    TAI_KHAM = 'BỆNH 1'
}
